[package]
name = "244_b_project"
version = "0.0.1"
authors = ["Michaela Murray", "Isaac Westlund", "Guy Wuollet Jr"]

[dependencies]
rust-crypto = "^0.2"
rand = "^0.5"
queue = "0.3.1"

[lib]
name = "service"
path = "src/lib.rs"


